const USER_CHANGE_AFTER_GOOGLE_REGISTER = 'USER_CHANGE_AFTER_GOOGLE_REGISTER'
const USER_CHANGE_AFTER_REGISTER = 'USER_CHANGE_AFTER_REGISTER'
const USER_NAVIGATE_PAGE = 'USER_NAVIGATE_PAGE'
const USER_CLEAR = 'USER_CLEAR'

const PRODUCT_NAVIGATE_PRODUCT_DETAIL = 'PRODUCT_NAVIGATE_PRODUCT_DETAIL'

const CATEGORY_NAVIGATE_LIST = 'CATEGORY_NAVIGATE_LIST'

const ADDRESS_UPDATE = 'ADDRESS_UPDATE'
const ADDRESS_CLEAR = 'ADDRESS_CLEAR'

const USER_NAVIGATE_CONTACT = 'USER_NAVIGATE_CONTACT'

const CART_NAVIGATE_CHECKOUT = 'CART_NAVIGATE_CHECKOUT'

export {
  USER_CHANGE_AFTER_GOOGLE_REGISTER,
  USER_CHANGE_AFTER_REGISTER,
  USER_NAVIGATE_PAGE,
  USER_CLEAR,
  PRODUCT_NAVIGATE_PRODUCT_DETAIL,
  CATEGORY_NAVIGATE_LIST,
  ADDRESS_UPDATE,
  ADDRESS_CLEAR,
  USER_NAVIGATE_CONTACT,
  CART_NAVIGATE_CHECKOUT,
}
