const USER_CHANGE_AFTER_GOOGLE_REGISTER = 'USER_CHANGE_AFTER_GOOGLE_REGISTER'
const USER_CHANGE_AFTER_REGISTER = 'USER_CHANGE_AFTER_REGISTER'
const USER_NAVIGATE_RESET_PASSWORD = 'USER_NAVIGATE_RESET_PASSWORD'
export const USER_CHANGE = 'USER_CHANGE'
const USER_CLEAR = 'USER_CLEAR'

const PRODUCT_NAVIGATE_PRODUCT_DETAIL = 'PRODUCT_NAVIGATE_PRODUCT_DETAIL'
const CATEGORY_NAVIGATE_LIST = 'CATEGORY_NAVIGATE_LIST'

export {
  USER_CHANGE_AFTER_GOOGLE_REGISTER,
  USER_CHANGE_AFTER_REGISTER,
  USER_NAVIGATE_RESET_PASSWORD,
  USER_CLEAR,
  PRODUCT_NAVIGATE_PRODUCT_DETAIL,
  CATEGORY_NAVIGATE_LIST,
}
